### ISSUE TITLE
Regarding Thresholding 

### ISSUE THREAD

**Issue by aflah02** [swj0419/detect-pretrain-code#3]
First of all really cool work!
In Section 4.3 the last line under implementation details is - "As we report the AUC score as our metric, we don’t need to determine the threshold ϵ."
Can you please explain this a bit? This might be a really trivial thing but I'm a bit confused by this

**Comment by swj0419** [comment]
Thanks for your interest in our work!

To explain, the AUC score represents the likelihood that the model will rank a randomly chosen positive instance higher than a randomly chosen negative one. When using the AUC as a metric, the specific choice of threshold ϵ is not necessary because AUC evaluates the quality of the model's predictions across all possible thresholds, rather than at any specific point.

**Comment by aflah02** [comment]
Thank you, this clears it up!
